package com.drew.model.bean;

import com.alibaba.fastjson.JSON;
import com.drew.model.Blog;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public class BlogBean {

    private java.lang.Integer id;

    private java.lang.String title;

    private java.lang.String content;


	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setContent(java.lang.String content) {
		this.content = content;
	}

	public java.lang.String getContent() {
		return this.content;
	}


    // model ---> bean
	public void modelToBean(Blog model){
        setId((java.lang.Integer) model.get("id"));
        setTitle((java.lang.String) model.get("title"));
        setContent((java.lang.String) model.get("content"));
	}

    public String toJson(){
        return JSON.toJSONString(this);
    }

}
