package com.drew.model.dao;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.Page;

import com.drew.model.*;
import com.drew.model.bean.BlogBean;
import com.jfinal.plugin.activerecord.Table;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BlogDao {

    static final Object[] NULL_PARA_ARRAY = new Object[0];

    // --------------------------------- 普通 查询 find ---------------------------------
    public List<BlogBean> find(String sql) {
        List<Blog> modelList = Blog.dao.find(sql);
        return modelListToBean(modelList);
    }

    public List<BlogBean> find(String sql, Object... paras) {
        List<Blog> modelList = Blog.dao.find(sql, paras);
        return modelListToBean(modelList);
    }
    
    
    // --------------------------------- 主键 查询 findById ---------------------------------
    public BlogBean findById(Object idValue) {
        Blog model = Blog.dao.findById(idValue);
        return modelToBean(model);
    }

    public BlogBean findById(Object... idValues) {
        Blog model = Blog.dao.findById(idValues);
        return modelToBean(model);
    }

    // --------------------------------- 主键 查询 指定某列或某几列 ---------------------------------
    public BlogBean findByIdLoadColumns(Object idValue, String columns) {
        Blog model = Blog.dao.findByIdLoadColumns(new Object[]{idValue}, columns);
        return modelToBean(model);
    }

    public BlogBean findByIdLoadColumns(Object[] idValues, String columns) {
        Blog model = Blog.dao.findByIdLoadColumns(idValues, columns);
        return modelToBean(model);
    }

    // --------------------------------- 查询 第一条 findFirst ---------------------------------
    public BlogBean findFirst(String sql) {
        Blog model = Blog.dao.findFirst(sql, NULL_PARA_ARRAY);
        return modelToBean(model);
    }

    public BlogBean findFirst(String sql, Object... paras) {
        Blog model = Blog.dao.findFirst(sql, paras);
        return modelToBean(model);
    }

    // --------------------------------- 分页 查询 paginate ---------------------------------
    public Page<BlogBean> paginate(int pageNumber, int pageSize, String select, String sqlExceptSelect) {
        Page<Blog> pageModel = Blog.dao.paginate(pageNumber, pageSize, select, sqlExceptSelect, NULL_PARA_ARRAY);
        return pageModelToBean(pageModel);
    }

    public Page<BlogBean> paginate(int pageNumber, int pageSize, String select, String sqlExceptSelect, Object... paras) {
        Page<Blog> pageModel = Blog.dao.paginate(pageNumber, pageSize, null, select, sqlExceptSelect, paras);
        return pageModelToBean(pageModel);
    }

    public Page<BlogBean> paginate(int pageNumber, int pageSize, boolean isGroupBySql, String select, String sqlExceptSelect, Object... paras) {
        Blog model = new Blog();
        Page<Blog> pageModel = Blog.dao.paginate(pageNumber, pageSize, isGroupBySql, select, sqlExceptSelect, paras);
        return pageModelToBean(pageModel);
    }

    public Page<BlogBean> paginateByFullSql(int pageNumber, int pageSize, String totalRowSql, String findSql, Object... paras) {
        Blog model = new Blog();
        Page<Blog> pageModel = Blog.dao.paginateByFullSql(pageNumber, pageSize, null, totalRowSql, findSql, paras);
        return pageModelToBean(pageModel);
    }

    public Page<BlogBean> paginateByFullSql(int pageNumber, int pageSize, boolean isGroupBySql, String totalRowSql, String findSql, Object... paras) {
        Page<Blog> pageModel = Blog.dao.paginateByFullSql(pageNumber, pageSize, isGroupBySql, totalRowSql, findSql, paras);
        return pageModelToBean(pageModel);

    }

    // --------------------------------- 插入 save ---------------------------------
    public boolean save(BlogBean bean) {
        // model --> bean ,用 bean 调用save（）方法
        Blog model = new Blog();
        model.beanToModel(bean);
        return model.save();
    }

    // --------------------------------- 删除 delete ---------------------------------
    public boolean delete(BlogBean bean) {
        Blog model = new Blog();
        model.beanToModel(bean);
        return model.delete();
    }
    // --------------------------------- 主键 删除 delete ---------------------------------
    public boolean deleteById(BlogBean bean, Object idValue) {
        Blog model = new Blog();
        model.beanToModel(bean);
        return model.deleteById(idValue);
    }

    public boolean deleteById(BlogBean bean, Object... idValues) {
        Blog model = new Blog();
        model.beanToModel(bean);
        return model.deleteById(idValues);
    }

    // --------------------------------- 更新 update ---------------------------------

    public boolean update(BlogBean bean) {
        Blog model = new Blog();
        model.beanToModel(bean);
        return model.update();
    }

    // --------------------------------- 查询结果 model 转 bean ---------------------------------
    private BlogBean modelToBean(Blog model) {
        BlogBean bean = new BlogBean();
        bean.modelToBean(model);
        return bean;
    }

    private List<BlogBean> modelListToBean(List<Blog> modelList) {
        List<BlogBean> beanList = new ArrayList<BlogBean>();
        for (Blog model : modelList) {
            BlogBean bean = new BlogBean();
            bean.modelToBean(model);
            beanList.add(bean);
        }
        return beanList;
    }

    private Page<BlogBean> pageModelToBean(Page<Blog> pageModel) {
        //获取 查询结果的 Map内容
        List<Blog> modelList = pageModel.getList();
        List<BlogBean> beanList = modelListToBean(modelList);
        //创建 新的返回对象
        return new Page<>(beanList, pageModel.getPageNumber(), pageModel.getPageSize(), pageModel.getTotalPage(), pageModel.getTotalRow());
    }

}
